const albumsActionTypes = {
  GET_ALBUMS_START: "GET_ALBUMS_START",
  GET_ALBUMS_SUCCESS: "GET_ALBUMS_SUCCESS",
  GET_ALBUMS_FAILURE: "GET_ALBUMS_FAILURE",
  GET_ALBUM_START: "GET_ALBUM_START",
  GET_ALBUM_SUCCESS: "GET_ALBUM_SUCCESS",
  GET_ALBUM_FAILURE: "GET_ALBUM_FAILURE",
  POST_ALBUM_START: "POST_ALBUM_START",
  POST_ALBUM_SUCCESS: "POST_ALBUM_SUCCESS",
  POST_ALBUM_FAILURE: "POST_ALBUM_FAILURE",
  DELETE_ALBUM_START: "DELETE_ALBUM_START",
  DELETE_ALBUM_SUCCESS: "DELETE_ALBUM_SUCCESS",
  DELETE_ALBUM_FAILURE: "DELETE_ALBUM_FAILURE",
  POST_TRACK_START: "POST_TRACK_START",
  POST_TRACK_SUCCESS: "POST_TRACK_SUCCESS",
  POST_TRACK_FAILURE: "POST_TRACK_FAILURE",
  DELETE_TRACK_START: "DELETE_TRACK_START",
  DELETE_TRACK_SUCCESS: "DELETE_TRACK_SUCCESS",
  DELETE_TRACK_FAILURE: "DELETE_TRACK_FAILURE",
};

export default albumsActionTypes;
